kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helm-clientgo-example
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - configmaps
  - services
  - namespaces
  - deployments
  - jobs
  verbs:
  - '*'
- apiGroups:
  - "apps"
  resources:
  - deployments
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - serviceaccounts
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-clientgo-example
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-clientgo-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-clientgo-example
subjects:
- kind: ServiceAccount
  name: helm-clientgo-example
  namespace: default
