apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
      - image: helm-clientgo-example
        name: helm-clientgo-example
        resources: {}
        imagePullPolicy: Never
      serviceAccountName: helm-clientgo-example 
status: {}
